export const languageCodes = [
    { value: "es1", label: "Spanish" },
    { value: "mlg", label: "Multilingual" },
    { value: "zh", label: "Chinese (Traditional)" },
    { value: "zh1", label: "Chinese (Simplified)" },
    { value: "aa", label: "Afar" },
    { value: "ab", label: "Abkhazian" },
    { value: "ae", label: "Avestan" },
    { value: "af", label: "Afrikaans" },
    { value: "ak", label: "Akan" },
    { value: "am", label: "Amharic" },
    { value: "an", label: "Aragonese" },
    { value: "ar", label: "Arabic" },
    { value: "as", label: "Assamese" },
    { value: "av", label: "Avaric" },
    { value: "ay", label: "Aymara" },
    { value: "az", label: "Azerbaijani" },
    { value: "ba", label: "Bashkir" },
    { value: "be", label: "Belarusian" },
    { value: "bg", label: "Bulgarian" },
    { value: "bh", label: "Bihari languages" },
    { value: "bi", label: "Bislama" },
    { value: "bm", label: "Bambara" },
    { value: "bn", label: "Bengali" },
    { value: "bo", label: "Tibetan" },
    { value: "br", label: "Breton" },
    { value: "bs", label: "Bosnian" },
    { value: "ca", label: "Catalan; Valencian" },
    { value: "ce", label: "Chechen" },
    { value: "ch1", label: "Chamorro" },
    { value: "co", label: "Corsican" },
    { value: "ch2", label: "Chin" },
    { value: "ch3", label: "Chuukese" },
    { value: "cr", label: "Cree" },
    { value: "cs", label: "Czech" },
    { value: "cv", label: "Chuvash" },
    { value: "cy", label: "Welsh" },
    { value: "da", label: "Danish" },
    { value: "fa1", label: "Dari" },
    { value: "de", label: "German" },
    { value: "dv1", label: "Divehi" },
    { value: "dv2", label: "Dhivehi" },
    { value: "dv3", label: "Maldivian" },
    { value: "dz", label: "Dzongkha" },
    { value: "ee", label: "Ewe" },
    { value: "el", label: "Greek" },
    { value: "en", label: "English" },
    { value: "eo", label: "Esperanto" },
    { value: "es2", label: "Castilian" },
    { value: "et", label: "Estonian" },
    { value: "eu", label: "Basque" },
    { value: "fa2", label: "Persian" },
    { value: "ff", label: "Fulah" },
    { value: "fi", label: "Finnish" },
    { value: "fj", label: "Fijian" },
    { value: "fo", label: "Faroese" },
    { value: "fr", label: "French" },
    { value: "fy", label: "Western Frisian" },
    { value: "ga", label: "Irish" },
    { value: "gd", label: "Gaelic" },
    { value: "gd1", label: "Scomttish Gaelic" },
    { value: "gl", label: "Galician" },
    { value: "gn", label: "Guarani" },
    { value: "gu", label: "Gujarati" },
    { value: "gv", label: "Manx" },
    { value: "ha", label: "Hausa" },
    { value: "he", label: "Hebrew" },
    { value: "hi", label: "Hindi" },
    { value: "ho", label: "Hiri Motu" },
    { value: "hr", label: "Croatian" },
    { value: "ht", label: "Haitiane" },
    { value: "ht1", label: "Haitian Creole" },
    { value: "hu", label: "Hungarian" },
    { value: "hy", label: "Armenian" },
    { value: "hz", label: "Hmong" },
    {
        value: "ia",
        label: "Interlingua"
    },
    { value: "th1", label: "Thai" },
    { value: "id", label: "Indonesian" },
    { value: "ie1", label: "Occidental" },
    { value: "ie2", label: "Interlingue" },
    { value: "ig", label: "Igbo" },
    { value: "ii1", label: "Nuosu" },
    { value: "ii2", label: "Sichuan Yi" },
    { value: "ik", label: "Inupiaq" },
    { value: "io", label: "Ido" },
    { value: "is", label: "Icelandic" },
    { value: "it", label: "Italian" },
    { value: "iu", label: "Inuktitut" },
    { value: "ja", label: "Japanese" },
    { value: "jv", label: "Javanese" },
    { value: "ka1", label: "Georgian" },
    { value: "ka2", label: "Karen" },
    { value: "ka3", label: "Karenni" },
    { value: "kg", label: "Kongo" },
    { value: "ki1", label: "Gikuyu" },
    { value: "kj1", label: "Kwanyama" },
    { value: "ki2", label: "Kikuyu" },
    { value: "kj2", label: "Kuanyama" },
    { value: "kk", label: "Kazakh" },
    { value: "kl1", label: "Kalaallisut" },
    { value: "kl2", label: "Greenlandic" },
    { value: "km1", label: "Khmer" },
    { value: "km2", label: "Central Khmer" },
    { value: "kn", label: "Kannada" },
    { value: "ko", label: "Korean" },
    { value: "kr", label: "Kanuri" },
    { value: "ks", label: "Kashmiri" },
    { value: "ku", label: "Kurdish" },
    { value: "kv", label: "Komi" },
    { value: "kw", label: "Cornish" },
    { value: "ky", label: "Kyrgyz" },
    { value: "ky1", label: "Kirghiz" },
    { value: "la", label: "Latin" },
    { value: "lb1", label: "Letzeburgesch" },
    { value: "lb2", label: "Luxembourgish" },
    { value: "lg", label: "Ganda" },
    { value: "li1", label: "Limburgan" },
    { value: "li2", label: "Limburger" },
    { value: "li3", label: "Limburgish" },
    { value: "ln", label: "Lingala" },
    { value: "lo", label: "Lao" },
    { value: "lt", label: "Lithuanian" },
    { value: "lu", label: "Luba-Katanga" },
    { value: "lv", label: "Latvian" },
    { value: "mg", label: "Malagasy" },
    { value: "mh", label: "Marshallese" },
    { value: "mi", label: "Maori" },
    { value: "mk", label: "Macedonian" },
    { value: "ml", label: "Malayalam" },
    { value: "mn", label: "Mongolian" },
    { value: "mr", label: "Marathi" },
    { value: "ms", label: "Malay" },
    { value: "mt", label: "Maltese" },
    { value: "my", label: "Burmese" },
    { value: "na", label: "Nauru" },
    { value: "nb", label: "Bokmål, Norwegian" },
    { value: "nb1", label: "Norwegian Bokmål" },
    { value: "nd", label: "Ndebele, North" },
    { value: "nd1", label: "North Ndebele" },
    { value: "ne", label: "Nepali" },
    { value: "ng", label: "Ndonga" },
    { value: "nl", label: "Flemish" },
    { value: "nl1", label: "Dutch" },
    { value: "nn", label: "Norwegian Nynorsk" },
    { value: "nn1", label: "Nynorsk, Norwegian" },
    { value: "no", label: "Norwegian" },
    { value: "nr", label: "Ndebele, South" },
    { value: "nr1", label: "South Ndebele" },
    { value: "nv", label: "Navajo" },
    { value: "nv1", label: "Navaho" },
    { value: "ny", label: "Chichewa" },
    { value: "ny1", label: "Chewa" },
    { value: "ny2", label: "Nyanja" },
    { value: "oc", label: "Occitan (post 1500)" },
    { value: "oj", label: "Ojibwa" },
    { value: "om", label: "Oromo" },
    { value: "or", label: "Oriya" },
    { value: "os", label: "Ossetic" },
    { value: "os1", label: "Ossetian" },
    { value: "pa", label: "Punjabi" },
    { value: "pa1", label: "Panjabi" },
    { value: "pi", label: "Pali" },
    { value: "pl", label: "Polish" },
    { value: "ps", label: "Pashto" },
    { value: "ps2", label: "Pushto" },
    { value: "pt", label: "Portuguese" },
    { value: "qu", label: "Quechua" },
    { value: "rm", label: "Romansh" },
    { value: "rn", label: "Rundi" },
    { value: "ro", label: "Romanian" },
    { value: "ro1", label: "Moldavian" },
    { value: "ro2", label: "Moldovan" },
    { value: "ru", label: "Russian" },
    { value: "rw", label: "Kinyarwanda" },
    { value: "sa", label: "Sanskrit" },
    { value: "sc", label: "Sardinian" },
    { value: "sd", label: "Sindhi" },
    { value: "se", label: "Northern Sami" },
    { value: "sg", label: "Sango" },
    { value: "si", label: "Sinhala" },
    { value: "sk", label: "Slovak" },
    { value: "sl", label: "Slovenian" },
    { value: "sm", label: "Samoan" },
    { value: "sn", label: "Shona" },
    { value: "so", label: "Somali" },
    { value: "sq", label: "Albanian" },
    { value: "sr", label: "Serbian" },
    { value: "ss", label: "Swati" },
    { value: "st", label: "Sotho, Southern" },
    { value: "su", label: "Sundanese" },
    { value: "sv", label: "Swedish" },
    { value: "sw", label: "Swahili" },
    { value: "ta", label: "Tamil" },
    { value: "te", label: "Telugu" },
    { value: "tg", label: "Tajik" },
    { value: "th2", label: "Thai" },
    { value: "ti", label: "Tigrinya" },
    { value: "tk", label: "Turkmen" },
    { value: "tl", label: "Tagalog" },
    { value: "tn", label: "Tswana" },
    { value: "to", label: "Tonga (Tonga Islands)" },
    { value: "tr", label: "Turkish" },
    { value: "ts", label: "Tsonga" },
    { value: "tt", label: "Tatar" },
    { value: "tw", label: "Twi" },
    { value: "ty", label: "Tahitian" },
    { value: "ug", label: "Uyghur" },
    { value: "ug1", label: "Uighur" },
    { value: "uk", label: "Ukrainian" },
    { value: "ur", label: "Urdu" },
    { value: "uz", label: "Uzbek" },
    { value: "ve", label: "Venda" },
    { value: "vi", label: "Vietnamese" },
    { value: "vo", label: "Volapük" },
    { value: "wa", label: "Walloon" },
    { value: "wo", label: "Wolof" },
    { value: "xh", label: "Xhosa" },
    { value: "yi", label: "Yiddish" },
    { value: "yo", label: "Yoruba" },
    { value: "za", label: "Chuang" },
    { value: "za1", label: "Zhuang" },
    { value: "zu", label: "Zulu" },
]

export const featuredLanguages = [
    { value: "es1-f", label: "Spanish" },
    { value: "mlg-f", label: "Multilingual" },
    { value: "zh-f", label: "Chinese (Traditional)" },
    { value: "zh1-f", label: "Chinese (Simplified)" },
]